config/routes.rb
Store::Application.routes.draw do

  devise_for :users

  resources :products do
    resources :comments, only: [:create]
  end
  root :to => 'products#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :photo
  belongs_to :attachable, polymorphic: true
  has_attached_file :photo, styles: { medium: "300x300", thumb: "100x100" }, default_url: "missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :body, :product_id, :user_id
  belongs_to :product
  belongs_to :user

end

app/models/product.rb
class Product < ActiveRecord::Base

  PER_PAGE_NUMBER = 20
  attr_accessible :description, :name, :attachments_attributes
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: :true, length: { minimum: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :comments, dependent: :destroy
  has_many :products, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_product

  def create
    @comment = @product.comments.new(params[:comment])
    @comment.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Your comment has been added.') }
        format.js
      else
        format.html { redirect_to @product }
        format.js
      end
    end
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_product, only: [:show, :edit, :update, :destroy]
  before_filter :validate_product_user!, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.order('created_at DESC').page(params[:page]).per(Product::PER_PAGE_NUMBER)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comment = Comment.new
    @comments = @product.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @attachment = @product.attachments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private

  def get_product
    @product = Product.find(params[:id])
  end

  def validate_product_user!
    redirect_to root_path, alert: "Invalid Access" unless @product.user_id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def is_allowed(id)
    current_user.id == id
  end

end

app/views/comments/_comment.html.erb
<div>
  <strong>Name:</strong>
  <%= comment.user.email%>
</div>

<div>
  <strong>Comment:</strong>
  <%= comment.body %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@product, @comment], remote: true do |f| %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, required: true, size: '10x10' %>
  </div>
  <%= f.hidden_field :product_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('.comment-page').append("<%= escape_javascript (render partial: 'comment', locals: { comment: @comment }) %>");
$('#comment_body').val('');

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand", style="max-width:50px; margin-top: -7px;"><%= image_tag "navbar.jpg" %></a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %><li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %><li>
          </ul>
          <ul class="nav pull-right">
            <li><%= 'Signed in as: ' %><%= current_user.email %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <div class='message'>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
      </div>
    <% end %>
    <div><%= render partial: 'layouts/header' %></div>
    <h2>The Art of Living</h2>
    <i>"We don't read and write poetry because it's cute. We read and write poetry because we are members of the human race. And the human race is filled with passion. And medicine, law, business, engineering, these are noble pursuits and necessary to sustain life. But poetry, beauty, romance, love, these are what we stay alive for."<i>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= nested_form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'textfield' %>
  </div>
  <%= f.fields_for :attachments do |attachment| %>
   <%= attachment.file_field :photo %>
   <%= attachment.link_to_remove "Remove this attachment", class:'btn btn-default btn-sm' %>
  <% end %>
  <div><%= f.link_to_add "Add new attachment", :attachments, class:'btn btn-default btn-sm' %></div>

  <div class="form-actions">
    <%= f.submit nil, class:'btn btn-primary' %>
    <%= link_to 'Cancel', products_path, class:'btn' %>
  </div>

<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Art & Literary Products</h1>
</div>
<h1>Editing product</h1>
<%= render 'form' %>
<%= link_to 'View Product', product_path, class:'btn btn-sm btn-success' %> |
<%= link_to 'Back', product_path, class:'btn btn-sm btn-info' %>

app/views/products/index.html.erb
<div class="page=header">
  <h1>Art & Literary Products</h1>
</div>

<%= link_to "Add a new product", new_product_path, class: 'btn btn-primary btn-info new-button' %>

<table class="table table-striped table-hover">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
  </tr>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= link_to product.name.titleize, product_path(product) %></td>
        <td><%= product.description %></td>
        <td><%= product.user.email %></td>
        <% if is_allowed(product.user.id) %>
          <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-success' %></td>
          <td><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm:'Are you sure?' }, class: 'btn btn-primary btn-danger' %></td>
        <% end %>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products %>
<br />

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: 'btn btn-success' %>

app/views/products/show.html.erb
<div id="notice"><%= notice %></div>
<div class="page-header">
  <h1>Art & Literary Products</h1>
</div>

<div class="product-name">
  <h2><strong><%= @product.name.titleize %></strong></h2>
</div>
<div class="form-actions">
  <div class="product-description">
    <h3>Description:</h3>
    <p><%= @product.description %></p>
  </div>
  <div class="product-attachments">
    <h3>Image:</h3>
    <% @product.attachments.each do |attachment| %>
      <%= image_tag attachment.photo.url(:medium) %>
    <% end %>
  </div>
  <div class="product-reviews">
    <h3>Comments:</h3>
    <div class='comment-page'>
      <%= render @comments %>
    </div>
    <h2> Add a comment </h2>
    <%= render 'comments/form' %>
  </div>
</div>

<% if is_allowed(@product.user.id) %>
  <%= link_to t('.edit', default: t("helpers.links.edit")), edit_product_path(@product), class: 'btn btn-sm btn-success' %>
<% end %>
<%= link_to t('.back', default: t("helpers.links.back")), products_path, class:'btn btn-sm btn-info'  %>